### ISSUE TITLE
[Bug Report] It instantly crashes

### ISSUE THREAD

**Issue by IntoTheVoid-900** [AxolotlClient/AxolotlClient-launcher#10]
**Describe the bug**
As soon as the game finishes downloading it instantly crashes

**To Reproduce**
1. Start 1.19
2. Have it say game ended

**Expected behavior**
Playing the game ig?

**Screenshots**

**Envroiment (please complete the following information):**
 - OS: Tested on Windows and Linux
 - Version 1.5.0

**Additional context**

**Comment by moehreag** [comment]
make sure you have selected a correct Java installation for 1.19 which requires Java 17+. I'm sorry it's buggy, but that's why it needs to be rewritten from scratch.
