### ISSUE TITLE
[Feature Request] Flatpak distribution?

### ISSUE THREAD

**Issue by IntoTheVoid-900** [AxolotlClient/AxolotlClient-launcher#9]
**Describe the feature you'd like to have implemented**
Can you please release this client as a Flatpak to Flathub? I appreciate how you already have Linux support via AppImages, but Flatpaks are a much better app distribution format. Flatpaks integrate into your system better, and they also have Steam Deck support.

**Additional context**
Side note, if you do consider Flatpaks, can you add [MidnightControls](https://github.com/TeamMidnightDust/MidnightControls) so the client is fully Steam Deck compatible?

**Comment by moehreag** [comment]
> Can you please release this client as a Flatpak to Flathub?

As soon as I (or someone else) have rewritten the launcher to work better, this will be planned. Only for this current one, I don't think it's worth it in its current state

**Comment by moehreag** [comment]
Flatpak support is being considered for the new launcher.
